apiVersion: apps/v1
kind: Deployment
metadata:
  name: zora-app
  labels:
    app: zora
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zora
  template:
    metadata:
      labels:
        app: zora
    spec:
      containers:
        - name: zora-container
          image: 192.168.10.222:5000/zora:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: nexus-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: zora-service
spec:
  selector:
    app: zora
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
