apiVersion: apps/v1
kind: Deployment
metadata:
  name: zora-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zora-app
  template:
    metadata:
      labels:
        app: zora-app
    spec:
      containers:
        - name: zora-app
          image: 192.168.10.222:5000/zora:1.0.XX  # Replace XX with actual build number via pipeline
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: zora-app-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: zora-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080  # Change if port is occupied

